### ISSUE TITLE
Automated web scraping script

### ISSUE THREAD

**Issue by anasm-17** [anasm-17/lyrics_transliteration#19]
## Task: Automated Web Scraping script
Make it automated such that the user can specify how many pairs of texts they want and the script can fetch the desired number or until a limit is reached.

### Requirements:

- [x] Documented python scraping script.
- [x] Adhere to robots.txt guidelines if any.
- [x] Add slight delay in loading different pages.
- [ ] User Inputs: `language`(this would be Chinese for our case), `lines` (lines to return)
- [ ] Output: dump the file in csv format to data/{`language`}_transliteration.csv directory. 

CSV Format of first 2 lines: 

|  | {`language`} | transliteration_pinyin |
|-|---------------|------------------|
|0| line_1 | line_1 transliteration |
|1| line_2| line_2 transliteration |

### Deadline:
26-Apr-2020 at 6 pm
