### ISSUE TITLE
Dash app with basic input and output boxes

### ISSUE THREAD

**Issue by anasm-17** [anasm-17/lyrics_transliteration#21]
## Task: Dash app with basic input and output boxes
Develop a basic dash app that has two text boxes, one for input text and the other for output text. this does not need to be integrated with any other functions yet but use your judgment to code expecting such integrations in the future.

### Requirements:
- [x] create a new branch for dash app
- [x] have the standard setup for the dash file as needed in that branch
- [x] Output (up to you, but you can use this as reference):
![img](https://github.com/anasm-17/lyrics_transliteration/raw/master/app-diagram_1-0.PNG)

### Deadline:
26-Apr-2020 at 6 pm

**Comment by jsleslie** [comment]
I've had an in progress version where the output box functionality wasn't working. Maybe you can help me solve the problem?
